DROP TABLE IF EXISTS users;

CREATE TABLE users (
    id SERIAL PRIMARY KEY,
    firstName VARCHAR (100) NOT NULL,
    lastName VARCHAR (100) NOT NULL,
    username VARCHAR (255) UNIQUE NOT NULL,
    password_hash VARCHAR (255) NOT NULL
);